name: archipelago
description: An Archipelago client library written in Dart
version: 0.2.0

environment:
  sdk: ^3.7.0

dependencies:
  web_socket_channel: ^3.0.2
  json_annotation: ^4.9.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^6.0.0
  mockito: ^5.4.5
  test: ^1.25.15
